#!/usr/bin/env bash
#nginx should listen at port 80
#when querrying nginx at its root with a get it must return a page with Hello World
sudo apt pdate
sudo apt-get -y -install nginx
echo "Hello World" | sudo tee /var/www/html/index.html
sudo /etc/init.d/nginx restart

