#!/usr/bin/env bash
#creating a 404-error page

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
rep_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/default permanent;"
sudo sed -i "s/server_name _;/$rep_string/" /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i "server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
sudo nginx -t
sudo service nginx restart
