#!/usr/bin/env bash
# Install haproxy

sudo apt-get install -y haproxy
echo "ENABLE=1" |sudo tee -a /etc/default/haproxy

cat << EOT | sudo tee -a /etc/haproxy/haproxy.cfg
# Inside  the etc/haproxy/config file, creae baknd and fontend

frontend 54.175.146.193
	timeout client 50000
	bind 0:80
	default_backend 54.175.146.193_backend

backend 54.175.146.193_backend
	timeout connect 5000
	timeout server 50000
	balance roundrobin
	server 233057-web-01 54.175.146.193:80 check
	server 233057-web-02 54.237.41.19:80 check
EOT

sudo service haproxy restart
