#!/usr/bin/env bash
#displays number from 1 to 100
#displays fizzbuzz when number is a multiple of 3 and 5
#displays Fizz for multiples of 3
#displays Buzz for multiples of 5
#else displays the number
for i in {1..100}
do
	if (( i % 3 == 0 && i % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( i % 3 == 0))
	then
		echo "Fizz"
	elif (( i % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done
