#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.
passwd_file="/etc/passwd"
while IFS=":" read -r username _ uid gid info home shell;
do
	group=$(getent group "$gid" | cut -d: -f1)
	command=$(basename "$shell")
	password=$(grep -oP "^$username:(.*?)(?=:)" /etc/shadow)
	echo "The user $username is part of the $group gang, lives in $home and rides $command."
	echo "User ID's place is protected by the passcode $password, more info about the user here: $info"
	echo
done < "$passwd_file"
