#!/usr/bin/env bash
#Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.
while IFS=: read -r user pass desc home shell;
do
	if [[ "$user" = "#"* || -z "$user" ]];
	then
		continue
	fi
	echo "The user $user is part of the GROUP_ID gang, lives in $home, and rides $shell."
	echo "USER ID's place is protected by the passcode $pass."
done < /etc/passwd
