#!/usr/bin/env bash
# groups visitors by IP and HTTP status code, and displays this data.
LOG_FILE="access.log"
awk '{print $1, $9}' "$LOG_FILE" | sort | uniq -c | sort -nr | awk '{print $1, $2, $3}'
